### ISSUE TITLE
[Feature]: support MFX_EXTBUFF_MASTERING_DISPLAY_COLOUR_VOLUME and MFX_EXTBUFF_CONTENT_LIGHT_LEVEL_INFO in AV1 decode and encode

### ISSUE THREAD

**Issue by xhaihao** [intel/vpl-gpu-rt#283]
### What Feature?

User may use MFX_EXTBUFF_MASTERING_DISPLAY_COLOUR_VOLUME and MFX_EXTBUFF_CONTENT_LIGHT_LEVEL_INFO to fetch / pass HDR parameters from / to oneVPL for hevc, we expect they can work for av1 too. 

### What's the usage scenario would be benifited?

Transcode for media delivery, Playback

### Do you want to contribute a patch to develop this feature?

None

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-64006 for further analysis.

**Comment by FurongZhang** [comment]
https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/encode_hw/av1/agnostic/base/av1ehw_base_hdr.cpp

https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/encode_hw/av1/agnostic/base/av1ehw_base_hdr.h

VPL GPU runtime open source has already supported it.

**Comment by xhaihao** [comment]
@FurongZhang  The link provided by you is for encoding only, we can't fetch hdr metadata via MFX_EXTBUFF_MASTERING_DISPLAY_COLOUR_VOLUME and MFX_EXTBUFF_CONTENT_LIGHT_LEVEL_INFO for av1 decoding.  This works for hevc decoding (see https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp)

**Comment by nyanmisaka** [comment]
> @FurongZhang The link provided by you is for encoding only, we can't fetch hdr metadata via MFX_EXTBUFF_MASTERING_DISPLAY_COLOUR_VOLUME and MFX_EXTBUFF_CONTENT_LIGHT_LEVEL_INFO for av1 decoding. This works for hevc decoding (see https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp)

The recent commit 0d0ba3c should have fix it. Then [this PR](https://github.com/intel-media-ci/ffmpeg/pull/674) for ffmpeg can continue.

**Comment by FurongZhang** [comment]
@nyanmisaka , thank you for the information. I knew that.
