### ISSUE TITLE
[Bug]: Fail to encode AV1 due to LLVM compiler

### ISSUE THREAD

**Issue by RinCat** [intel/vpl-gpu-rt#331]
### Which component impacted?

Encode

### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

Under Linux, when compile oneVPL-intel-gpu with LLVM/Clang (at least versions 14-17), the AV1 QSV encoder used by ffmpeg always failed with:

```
[AVHWDeviceContext @ 0x56408d82a800] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ().
[AVHWDeviceContext @ 0x56408d82a800] Driver not found in known nonstandard list, using standard behaviour.
[av1_qsv @ 0x56408c586cc0] Initialized an internal MFX session using hardware accelerated implementation
[av1_qsv @ 0x56408c586cc0] Using the variable bitrate (VBR) ratecontrol method
EHW Exception: unknown ext. buffer Id
[av1_qsv @ 0x56408c586cc0] Error initializing the encoder: unknown error (-1)
[vost#0:0/av1_qsv @ 0x56408c584d40] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
Error while filtering: Unknown error occurred
```

Which at https://github.com/intel/vpl-gpu-rt/blob/4ad0d7bbbc6c63d01a6df513823cb10cf0d9bc45/_studio/mfx_lib/shared/include/mfx_utils_extbuf.h#L61

The same code compiled with gcc works fine.

### What's the usage scenario when you are seeing the problem?

Transcode for media delivery

### What impacted?

AV1 hardware encoding not work when using LLVM/clang.

### Debug Information

I only provide the latest version, this problem is at least a year old and many different combinations have been tried.

1. 

- libva 2.21
- gmmlib 22.3.19
- libvpl 2.11.0
- oneVPL-intel-gpu 24.2.2
- ffmpeg 6.1.1
- Linux 6.9
- LLVM/Clang 14 - 17
- gcc 13.3.0

2. 
```
ls /dev/dri
./  ../  by-path/  card0  renderD128
```

3. 
```
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib64/va/drivers/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
Trying display: wayland
vainfo: VA-API version: 1.21 (libva 2.21.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.2.2 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
```

4. N/A
5. N/A

### Do you want to contribute a patch to fix the issue?

None

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-73841 for further analysis.

**Comment by Bossonor** [comment]
Hi @RinCat, thank you for helping to discover this issue. We've attempted to reproduce the issue you mentioned, but were unsuccessful. The versions we used are as follows, which are largely consistent with the versions you provided.
- libvlp 2.11.0
- oneVPl-intel-gpu latest-version
- FFmpeg 6.1.1
- Linux 6.8
- LLVM/Clang 14
Below is the command we used:
`sudo /usr/local/bin/ffmpeg -y -qsv_device /dev/dri/renderD128 -hwaccel qsv -hwaccel_output_format qsv -i input.mp4 -c:v av1_qsv -b:v 4M output.mkv`
If our command settings differ from yours, could you kindly share the command and input you used for us to reproduce the issue?
Additionally, would you be able to test the problematic buffer ID when you have some free time? We would like to offer a [debug.patch](https://github.com/user-attachments/files/15530443/debug.patch) for your consideration. Your assistance with this matter would be greatly appreciated.

**Comment by RinCat** [comment]
Hi, I attached error logs with the debug patch, which used the same command you provided , and build configuration. Thanks.
[build.log](https://github.com/user-attachments/files/15536903/build.log)
[debug.log](https://github.com/user-attachments/files/15536904/debug.log)

**Comment by Bossonor** [comment]
Hi @RinCat , thank you for providing the build configuration. Despite our efforts, we are still unable to reproduce the issue. Based on the buffer Id you provided, we located that header file **mfxav1.h** may not being included with LLVM/Clang compiler. We have prepared a reference [fix.patch](https://github.com/user-attachments/files/15572058/fix.patch). If it doesn't work, you can try including the corresponding header file in your environment to resolve this issue. Thanks.

**Comment by RinCat** [comment]
@Bossonor Thanks for the quick response, I do confirm the patch fixed the issue!

Will this patch be included in future releases or is this just a local issue in our environment?

```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_qsv) -> av1 (av1_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> vorbis (libvorbis))
Press [q] to stop, [?] for help
1162761556
1178817605
1195725617
1212369985
1280136257
1330794053
1346588229
1347245141
1380012089
1397312588
1397895489
1398162244
1414745170
1481982257
Output #0, matroska, to 'output.mkv':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso6iso2mp41
    encoder         : Lavf60.16.100
  Stream #0:0(und): Video: av1 (AV01 / 0x31305641), qsv(pc, bt2020nc/bt2020/smpte2084, progressive), 2560x1440 [SAR 1:1 DAR 16:9], q=2-31, 4000 kb/s, 60 fps, 1k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.31.102 av1_qsv
```

**Comment by Bossonor** [comment]
Thank you for trying the patch promptly and providing feedback. It appears that the issue may be related to environment configuration.

**Comment by RinCat** [comment]
Then I will report it to our upstream, thank you very much!

**Comment by Bossonor** [comment]
Hi @RinCat , could you please help to try 
[fix.patch](https://github.com/user-attachments/files/15721919/fixissue.patch)
 in your environment, thanks in advance!

**Comment by RinCat** [comment]
Hi @Bossonor, the new patch still got `EHW Exception: unknown ext. buffer Id`
