### ISSUE TITLE
error: ‘VAPictureVVC’ does not name a type[Bug]: 

### ISSUE THREAD

**Issue by GeorgeZaher** [intel/vpl-gpu-rt#343]
### Is it regression? Good in old configuration?

None

### What happened?

When I compile:

inux.cpp"
In file included from /mnt/c/Users/ASUS Vivobook/vpl-gpu-rt/_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp:30:
/usr/include/va/va_dec_vvc.h:91:5: error: ‘VAPictureVVC’ does not name a type; did you mean ‘VAPictureHEVC’?
   91 |     VAPictureVVC            CurrPic;
      |     ^~~~~~~~~~~~
      |     VAPictureHEVC
/usr/include/va/va_dec_vvc.h:93:5: error: ‘VAPictureVVC’ does not name a type; did you mean ‘VAPictureHEVC’?
   93 |     VAPictureVVC            ReferenceFrames[15];
      |     ^~~~~~~~~~~~
      |     VAPictureHEVC

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

unable to compile

### Debug Information

inux.cpp"
In file included from /mnt/c/Users/ASUS Vivobook/vpl-gpu-rt/_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp:30:
/usr/include/va/va_dec_vvc.h:91:5: error: ‘VAPictureVVC’ does not name a type; did you mean ‘VAPictureHEVC’?
   91 |     VAPictureVVC            CurrPic;
      |     ^~~~~~~~~~~~
      |     VAPictureHEVC
/usr/include/va/va_dec_vvc.h:93:5: error: ‘VAPictureVVC’ does not name a type; did you mean ‘VAPictureHEVC’?
   93 |     VAPictureVVC            ReferenceFrames[15];
      |     ^~~~~~~~~~~~
      |     VAPictureHEVC

### Do you want to contribute a patch to fix the issue?

Yes, I'm glad to submit a patch to fix it

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-75001 for further analysis.

**Comment by Jexu** [comment]
The issue could be solved by updating libva to the latest version. So I will close this issue now and pls reopen it again if still having any problems.
