### ISSUE TITLE
[Bug]: Decode Question About BitstreamDataFlag Flag

### ISSUE THREAD

**Issue by DaveHu-TVU** [intel/vpl-gpu-rt#354]
### Which component impacted?

Decode

### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

 We found a problem in our recent tests: if async=1, decoding a 1080P IDRframe, MFXVideoDECODE_DecodeFrameAsync returns -10(MFX_ERR_MORE_DATA), and if I change mfxBitstream.DataFlag from MFX_BITSTREAM_COMPLETE_FRAME to MFX_BITSTREAM_EOS, then it can be decoded normally.

Q1： Why decoding a 1080P IDR frame returns -10 when async=1 when mfxBitstream.DataFlag is MFX_BITSTREAM_COMPLETE_FRAME ?
Q2：What is the difference between MFX_BITSTREAM_COMPLETE_FRAME and MFX_BITSTREAM_EOS for decoder? 

Thanks!

### What's the usage scenario when you are seeing the problem?

Playback

### Debug Information

Hi ,
     We found a problem in our recent tests: if async=1, decoding a 1080P IDRframe, MFXVideoDECODE_DecodeFrameAsync returns -10(MFX_ERR_MORE_DATA), and if I change mfxBitstream.DataFlag from MFX_BITSTREAM_COMPLETE_FRAME to MFX_BITSTREAM_EOS, then it can be decoded normally.

Q1： Why decoding a 1080P IDR frame returns -10 when async=1 when mfxBitstream.DataFlag is MFX_BITSTREAM_COMPLETE_FRAME ?
Q2：What is the difference between MFX_BITSTREAM_COMPLETE_FRAME and MFX_BITSTREAM_EOS for decoder? 

Thanks!

![image](https://github.com/user-attachments/assets/1d506e35-8ea2-42b2-b48c-ddad2cd0b97c)

### Do you want to contribute a patch to fix the issue?

None

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-77162 for further analysis.

**Comment by Jexu** [comment]
1, As the description of the val spec, when flag 'MFX_BITSTREAM_COMPLETE_FRAME ' is set, completed bitstream data is required by vpl, when app sends pieces of bitstream for one frame in multi times, vpl may return MORE_DATA(-10) each time until getting completed bitstream data, so you may need to check if vpl really gets completed bitstream data in your case.
However, if flag 'MFX_BITSTREAM_EOS', it tells vpl no more bitstream data to process.
2, async number has impact on the thread num for syncOperation in vpl. SyncOperation -> vaSyncSurfaec -> waiting frame decoding done. Vpl will wait multi-frame decoding done by 'async num' thread in parallel.

**Comment by DaveHu-TVU** [comment]
Thanks @Jexu , 
For question 1, in fact if VPL decodes H.264 or H.265 encoded from the Ambarella‘s H2 chip, decoder will return -10 when the flag is MFX_BITSTREAM_COMPLETE_FRAME, 
and then I used ffmpeg to decode(soft decoder) this frame, it worked well.
and then I changed the flag to MFX_BITSTREAM_EOS, VPL can decode it well.

So there are new 2 quesions:
Q1:  the attached amba.zip is my test file, can you help analyze why VPL would consider this an incomplete frame? Or can you describe in detail what is the logic that VPL uses to determine if it is a complete frame?

Q2: if I change the flag from MFX_BITSTREAM_COMPLETE_FRAME to MFX_BITSTREAM_EOS, what are the potential risks of this for decoding?because when I tested sample_decode I found that 2023Q1's sample_decode use the MFX_BITSTREAM_EOS default.


For question 2, thanks, I goti the point.

[amba.zip](https://github.com/user-attachments/files/17812992/amba.zip)

**Comment by DaveHu-TVU** [comment]
Hi Jexu, 
      this is my test h265 file, amba_1080p50.h265 will return -10, but intel_1080p50.h265 will return 0.
to give you more test cases, can you please help analyze why VPL thinks amba_1080p50.h265 is not a complete frame?
thanks again!


[amba_1080p50.zip](https://github.com/user-attachments/files/17813281/amba_1080p50.zip)
[intel_1080p50.zip](https://github.com/user-attachments/files/17813282/intel_1080p50.zip)

**Comment by Jexu** [comment]
App calls api '[MFXVideoDECODE_DecodeFrameAsync](https://intel.github.io/libvpl/latest/API_ref/VPL_func_vid_decode.html#id11)' to feed vpl rt with bitstream data by multi times. The input bitstream bs can be of any size. If there are not enough bits to decode a frame, the function returns MFX_ERR_MORE_DATA.

In your case, **last second bs != null, but bs->data_size == 0**, it means app tells vpl having more bitstream data to process, but given zero data, then vpl return 'MFX_ERR_MORE_DATA' to require more bitstream data. So app tries to read more data from bitstream, but finds eof with no data anymore, then call api agine by setting bs=null to tell vpl no bitstream data, so far, vpl will consume all input saved bits in inside the buffer.

No matter which flag 'MFX_BITSTREAM_COMPLETE_FRAME' and 'MFX_BITSTREAM_EOS' is set, app may need to ensure where completed frame bitstream is sent to vpl to decode.
